spring:
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    defer-datasource-initialization: false
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:maindb
    username: sa
    password: password
  liquibase:
    enabled: true
    change-log: classpath:db/migrations/db.changelog-root.yaml
    default-schema: public
  server:
    profiles:
      active: test, hsqldb

server:
  port: 8081
  error:
    include-stacktrace: never
springdoc:
  api-docs:
    path: /api-docs

static-table:
  categories:
    Juguetes: 20
    Libros: 15
    Deportes: 5
    Comida: 25
    Ropa: 35
    Otros: 0

services-url:
  cart-url: "http://localhost:8080"
  user-url: "http://localhost:8082"

feature-flags:
  callUserEnabled: true
  callCartEnabled: true

logging:
  level:
    org.springframework.web: "DEBUG"
    tomcat: "DEBUG"
    liquibase: "INFO"

