insert into product (name, category, description, price, stock) values ('Ara ararauna', 'Juguetes', 'lorem vitae mattis nibh ligula nec sem duis', 1936.53, 1);
insert into product (name, category, description, price, stock) values ('Hyaena brunnea', 'Juguetes', 'ultrices posuere cubilia', 2957.95, 2);
insert into product (name, category, description, price, stock) values ('Corythornis cristata', 'Juguetes', 'aenean auctor gravida sem praesent id massa id nisl venenatis', 818.91, 3);
insert into product (name, category, description, price, stock) values ('Thalasseus maximus', 'Juguetes', 'magna at nunc', 2952.0, 4);
insert into product (name, category, description, price, stock) values ('Papio ursinus', 'Juguetes', 'rutrum rutrum neque aenean', 2899.45, 5);
insert into product (name, category, description, price, stock) values ('Varanus sp.', 'Juguetes', 'ullamcorper augue a suscipit nulla elit ac', 2113.77, 6);
insert into product (name, category, description, price, stock) values ('Pseudoleistes virescens', 'Juguetes', 'nunc rhoncus dui vel sem sed sagittis', 2106.96, 7);
insert into product (name, category, description, price, stock) values ('Tetracerus quadricornis', 'Juguetes', 'odio condimentum id luctus nec', 1991.61, 8);
insert into product (name, category, description, price, stock) values ('Lamprotornis nitens', 'Juguetes', 'ultrices vel augue vestibulum ante ipsum primis', 1094.72, 9);
insert into product (name, category, description, price, stock) values ('Alligator mississippiensis', 'Juguetes', 'odio porttitor id consequat in consequat ut nulla', 478.86, 10);
insert into product (name, category, description, price, stock) values ('Nycticorax nycticorax', 'Juguetes', 'gravida nisi at nibh', 614.05, 11);
insert into product (name, category, description, price, stock) values ('Ceratotherium simum', 'Juguetes', 'lacus purus aliquet at feugiat non pretium', 46.73, 12);
insert into product (name, category, description, price, stock) values ('Dusicyon thous', 'Juguetes', 'morbi a ipsum integer', 1088.75, 13);
insert into product (name, category, description, price, stock) values ('Lybius torquatus', 'Juguetes', 'sollicitudin mi sit amet lobortis sapien sapien non mi integer', 2320.62, 14);
insert into product (name, category, description, price, stock) values ('Laniarius ferrugineus', 'Juguetes', 'rutrum ac lobortis vel dapibus', 1273.2, 15);
insert into product (name, category, description, price, stock) values ('Petaurus norfolcensis', 'Juguetes', 'velit nec nisi vulputate nonummy maecenas tincidunt lacus', 1439.98, 16);
insert into product (name, category, description, price, stock) values ('Leptoptilos crumeniferus', 'Juguetes', 'nullam orci pede venenatis', 2474.1, 17);
insert into product (name, category, description, price, stock) values ('Capreolus capreolus', 'Juguetes', 'ac neque duis bibendum', 659.88, 18);
insert into product (name, category, description, price, stock) values ('Fulica cristata', 'Juguetes', 'odio justo sollicitudin ut suscipit a', 1759.25, 19);
insert into product (name, category, description, price, stock) values ('Drymarchon corias couperi', 'Juguetes', 'dui vel sem sed sagittis nam congue risus', 2339.91, 20);
insert into product (name, category, description, price, stock) values ('Tachyglossus aculeatus', 'Juguetes', 'nisl duis ac', 106.6, 21);
insert into product (name, category, description, price, stock) values ('Physignathus cocincinus', 'Juguetes', 'quam fringilla rhoncus mauris enim', 1255.81, 22);
insert into product (name, category, description, price, stock) values ('Gekko gecko', 'Juguetes', 'duis bibendum felis sed interdum venenatis turpis enim blandit', 527.61, 23);
insert into product (name, category, description, price, stock) values ('Panthera leo', 'Juguetes', 'sapien cum sociis natoque penatibus et', 2846.07, 24);
insert into product (name, category, description, price, stock) values ('Pycnonotus nigricans', 'Juguetes', 'in sapien', 2835.0, 25);
insert into product (name, category, description, price, stock) values ('Francolinus coqui', 'Juguetes', 'eleifend pede libero quis', 1004.45, 26);
insert into product (name, category, description, price, stock) values ('Podargus strigoides', 'Juguetes', 'lacinia nisi venenatis tristique', 2571.43, 27);
insert into product (name, category, description, price, stock) values ('Xerus sp.', 'Juguetes', 'aliquam augue quam sollicitudin vitae', 2069.74, 28);
insert into product (name, category, description, price, stock) values ('Ploceus rubiginosus', 'Juguetes', 'vulputate ut ultrices vel augue vestibulum ante ipsum', 2987.09, 29);
insert into product (name, category, description, price, stock) values ('Lasiorhinus latifrons', 'Juguetes', 'sem duis', 114.17, 30);
insert into product (name, category, description, price, stock) values ('Trichosurus vulpecula', 'Juguetes', 'ante ipsum', 164.56, 31);
insert into product (name, category, description, price, stock) values ('Dendrocitta vagabunda', 'Juguetes', 'enim leo rhoncus sed vestibulum sit amet cursus', 951.28, 32);
insert into product (name, category, description, price, stock) values ('Macaca mulatta', 'Juguetes', 'et ultrices', 49.53, 33);
insert into product (name, category, description, price, stock) values ('Tachyglossus aculeatus', 'Juguetes', 'dui luctus rutrum nulla tellus in sagittis dui vel', 2275.88, 34);
insert into product (name, category, description, price, stock) values ('Aonyx capensis', 'Juguetes', 'integer a nibh in quis justo maecenas', 2139.58, 35);
insert into product (name, category, description, price, stock) values ('Varanus sp.', 'Juguetes', 'ut tellus nulla ut erat id mauris vulputate elementum', 1706.96, 36);
insert into product (name, category, description, price, stock) values ('Connochaetus taurinus', 'Juguetes', 'porttitor id', 2366.93, 37);
insert into product (name, category, description, price, stock) values ('unavailable', 'Juguetes', 'penatibus et magnis dis parturient montes nascetur ridiculus', 1538.05, 38);
insert into product (name, category, description, price, stock) values ('Mazama gouazoubira', 'Juguetes', 'pellentesque ultrices phasellus id sapien', 2321.87, 39);
insert into product (name, category, description, price, stock) values ('Pycnonotus nigricans', 'Juguetes', 'at turpis donec posuere', 1059.36, 40);
insert into product (name, category, description, price, stock) values ('Ceratotherium simum', 'Juguetes', 'pede venenatis non sodales sed tincidunt eu', 1931.18, 41);
insert into product (name, category, description, price, stock) values ('Pseudalopex gymnocercus', 'Juguetes', 'in faucibus', 2868.55, 42);
insert into product (name, category, description, price, stock) values ('Lybius torquatus', 'Juguetes', 'nam dui proin', 1948.48, 43);
insert into product (name, category, description, price, stock) values ('Struthio camelus', 'Juguetes', 'ut nunc vestibulum', 2917.82, 44);
insert into product (name, category, description, price, stock) values ('Sarcorhamphus papa', 'Juguetes', 'mi integer ac neque duis bibendum morbi non quam', 2226.63, 45);
insert into product (name, category, description, price, stock) values ('Pelecans onocratalus', 'Juguetes', 'sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl', 1092.69, 46);
insert into product (name, category, description, price, stock) values ('Theropithecus gelada', 'Juguetes', 'orci luctus et ultrices posuere cubilia curae nulla', 289.87, 47);
insert into product (name, category, description, price, stock) values ('unavailable', 'Juguetes', 'vel dapibus at diam nam tristique tortor eu pede', 2613.41, 48);
insert into product (name, category, description, price, stock) values ('Ctenophorus ornatus', 'Juguetes', 'mattis odio donec vitae nisi', 1377.22, 49);
insert into product (name, category, description, price, stock) values ('Cracticus nigroagularis', 'Juguetes', 'amet eleifend', 2141.09, 50);
insert into product (name, category, description, price, stock) values ('Macropus giganteus', 'Juguetes', 'arcu sed augue aliquam erat volutpat', 2915.68, 51);
insert into product (name, category, description, price, stock) values ('Plectopterus gambensis', 'Juguetes', 'tincidunt eget tempus vel pede morbi porttitor lorem', 1163.81, 52);
insert into product (name, category, description, price, stock) values ('Buteo jamaicensis', 'Juguetes', 'donec vitae nisi nam', 2304.91, 53);
insert into product (name, category, description, price, stock) values ('Castor canadensis', 'Juguetes', 'integer a nibh in quis justo', 2890.85, 54);
insert into product (name, category, description, price, stock) values ('Butorides striatus', 'Juguetes', 'eleifend donec ut dolor morbi vel lectus in quam fringilla', 2836.58, 55);
insert into product (name, category, description, price, stock) values ('Trichoglossus haematodus moluccanus', 'Juguetes', 'sed interdum venenatis turpis enim blandit mi in porttitor pede', 1648.22, 56);
insert into product (name, category, description, price, stock) values ('Rangifer tarandus', 'Juguetes', 'semper interdum mauris ullamcorper purus sit amet nulla', 1348.93, 57);
insert into product (name, category, description, price, stock) values ('Colaptes campestroides', 'Juguetes', 'rhoncus mauris enim', 1884.02, 58);
insert into product (name, category, description, price, stock) values ('Loxodonta africana', 'Juguetes', 'ante ipsum', 1051.2, 59);
insert into product (name, category, description, price, stock) values ('Philetairus socius', 'Juguetes', 'aliquam erat volutpat in congue etiam', 645.1, 60);
insert into product (name, category, description, price, stock) values ('Stenella coeruleoalba', 'Juguetes', 'semper porta', 2638.89, 61);
insert into product (name, category, description, price, stock) values ('Theropithecus gelada', 'Juguetes', 'non sodales sed tincidunt eu', 2869.89, 62);
insert into product (name, category, description, price, stock) values ('unavailable', 'Juguetes', 'in quis justo maecenas rhoncus aliquam lacus morbi', 133.63, 63);
insert into product (name, category, description, price, stock) values ('Varanus sp.', 'Juguetes', 'ante ipsum primis in', 2214.34, 64);
insert into product (name, category, description, price, stock) values ('Canis lupus', 'Juguetes', 'vestibulum sagittis sapien cum sociis natoque penatibus et magnis', 2110.84, 65);
insert into product (name, category, description, price, stock) values ('Vulpes cinereoargenteus', 'Juguetes', 'eu est congue elementum in', 419.86, 66);
insert into product (name, category, description, price, stock) values ('Zonotrichia capensis', 'Juguetes', 'ac est lacinia nisi venenatis', 1568.44, 67);
insert into product (name, category, description, price, stock) values ('Canis lupus', 'Juguetes', 'donec ut dolor', 1131.11, 68);
insert into product (name, category, description, price, stock) values ('Felis silvestris lybica', 'Juguetes', 'sagittis nam congue risus semper porta volutpat quam', 432.87, 69);
insert into product (name, category, description, price, stock) values ('Stenella coeruleoalba', 'Juguetes', 'eros viverra eget', 1431.34, 70);
insert into product (name, category, description, price, stock) values ('Gabianus pacificus', 'Juguetes', 'vitae mattis nibh ligula nec sem duis aliquam convallis nunc', 2663.19, 71);
insert into product (name, category, description, price, stock) values ('Trichechus inunguis', 'Juguetes', 'ipsum primis in faucibus orci luctus et', 2900.11, 72);
insert into product (name, category, description, price, stock) values ('Psophia viridis', 'Juguetes', 'hac habitasse platea dictumst maecenas', 2000.74, 73);
insert into product (name, category, description, price, stock) values ('Pseudalopex gymnocercus', 'Juguetes', 'justo sit amet sapien dignissim vestibulum vestibulum ante', 990.38, 74);
insert into product (name, category, description, price, stock) values ('Hymenolaimus malacorhynchus', 'Juguetes', 'ipsum dolor sit amet consectetuer adipiscing elit proin risus praesent', 2950.99, 75);
insert into product (name, category, description, price, stock) values ('Microcebus murinus', 'Juguetes', 'aliquam quis turpis eget elit sodales scelerisque mauris sit amet', 147.45, 76);
insert into product (name, category, description, price, stock) values ('Panthera leo persica', 'Juguetes', 'interdum eu tincidunt in leo maecenas pulvinar lobortis', 1189.06, 77);
insert into product (name, category, description, price, stock) values ('Ictonyx striatus', 'Juguetes', 'donec diam neque vestibulum eget vulputate ut ultrices vel augue', 636.34, 78);
insert into product (name, category, description, price, stock) values ('Vombatus ursinus', 'Juguetes', 'phasellus id sapien in', 1870.57, 79);
insert into product (name, category, description, price, stock) values ('Bettongia penicillata', 'Juguetes', 'interdum eu tincidunt in leo maecenas pulvinar lobortis', 2051.69, 80);
insert into product (name, category, description, price, stock) values ('Spizaetus coronatus', 'Juguetes', 'lacinia sapien quis libero', 2060.58, 81);
insert into product (name, category, description, price, stock) values ('Isoodon obesulus', 'Juguetes', 'nam dui proin leo odio porttitor id consequat in consequat', 547.81, 82);
insert into product (name, category, description, price, stock) values ('Phylurus milli', 'Juguetes', 'quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum', 1598.53, 83);
insert into product (name, category, description, price, stock) values ('Cracticus nigroagularis', 'Juguetes', 'nisi volutpat eleifend donec ut', 371.05, 84);
insert into product (name, category, description, price, stock) values ('Tiliqua scincoides', 'Juguetes', 'feugiat et eros vestibulum ac est', 805.14, 85);
insert into product (name, category, description, price, stock) values ('Crax sp.', 'Juguetes', 'vivamus in felis', 943.43, 86);
insert into product (name, category, description, price, stock) values ('Corvus albicollis', 'Juguetes', 'in faucibus orci', 2813.41, 87);
insert into product (name, category, description, price, stock) values ('Pterocles gutturalis', 'Juguetes', 'scelerisque mauris sit amet eros suspendisse accumsan tortor quis', 1681.33, 88);
insert into product (name, category, description, price, stock) values ('Tursiops truncatus', 'Juguetes', 'ultrices mattis odio donec vitae nisi nam ultrices libero', 2343.45, 89);
insert into product (name, category, description, price, stock) values ('Catharacta skua', 'Juguetes', 'cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat', 1886.83, 90);
insert into product (name, category, description, price, stock) values ('Butorides striatus', 'Juguetes', 'integer pede justo lacinia eget tincidunt', 1292.18, 91);
insert into product (name, category, description, price, stock) values ('Dicrostonyx groenlandicus', 'Juguetes', 'vel est donec', 1761.06, 92);
insert into product (name, category, description, price, stock) values ('Eolophus roseicapillus', 'Juguetes', 'leo pellentesque ultrices mattis odio donec vitae nisi nam', 1427.0, 93);
insert into product (name, category, description, price, stock) values ('Loris tardigratus', 'Juguetes', 'magna vestibulum aliquet ultrices erat tortor', 2092.51, 94);
insert into product (name, category, description, price, stock) values ('Elephas maximus bengalensis', 'Juguetes', 'hendrerit at vulputate vitae nisl aenean lectus', 1122.34, 95);
insert into product (name, category, description, price, stock) values ('Zenaida galapagoensis', 'Juguetes', 'erat curabitur', 128.59, 96);
insert into product (name, category, description, price, stock) values ('Sarcophilus harrisii', 'Juguetes', 'ac tellus semper interdum mauris ullamcorper purus sit', 69.51, 97);
insert into product (name, category, description, price, stock) values ('Streptopelia senegalensis', 'Juguetes', 'in quis justo maecenas rhoncus aliquam lacus morbi quis tortor', 1270.23, 98);
insert into product (name, category, description, price, stock) values ('Dendrocitta vagabunda', 'Juguetes', 'id luctus nec', 2404.85, 99);
insert into product (name, category, description, price, stock) values ('Cebus nigrivittatus', 'Juguetes', 'nonummy maecenas', 2262.19, 100);
