insert into product (name, category, description, price, stock) values ('Ara ararauna', 'Juguetes', 'lorem vitae mattis nibh ligula nec sem duis', 1936.53, 1);
insert into product (name, category, description, price, stock) values ('Hyaena brunnea', 'Juguetes', 'ultrices posuere cubilia', 2957.95, 2);
insert into product (name, category, description, price, stock) values ('Corythornis cristata', 'Juguetes', 'aenean auctor gravida sem praesent id massa id nisl venenatis', 818.91, 3);
insert into product (name, category, description, price, stock) values ('Thalasseus maximus', 'Juguetes', 'magna at nunc', 2952.0, 4);
insert into product (name, category, description, price, stock) values ('Papio ursinus', 'Juguetes', 'rutrum rutrum neque aenean', 2899.45, 5);
insert into product (name, category, description, price, stock) values ('Varanus sp.', 'Juguetes', 'ullamcorper augue a suscipit nulla elit ac', 2113.77, 6);
insert into product (name, category, description, price, stock) values ('Pseudoleistes virescens', 'Juguetes', 'nunc rhoncus dui vel sem sed sagittis', 2106.96, 7);
insert into product (name, category, description, price, stock) values ('Tetracerus quadricornis', 'Juguetes', 'odio condimentum id luctus nec', 1991.61, 8);
insert into product (name, category, description, price, stock) values ('Lamprotornis nitens', 'Juguetes', 'ultrices vel augue vestibulum ante ipsum primis', 1094.72, 9);
insert into product (name, category, description, price, stock) values ('Alligator mississippiensis', 'Juguetes', 'odio porttitor id consequat in consequat ut nulla', 478.86, 10);
insert into product (name, category, description, price, stock) values ('Nycticorax nycticorax', 'Juguetes', 'gravida nisi at nibh', 614.05, 11);
insert into product (name, category, description, price, stock) values ('Ceratotherium simum', 'Juguetes', 'lacus purus aliquet at feugiat non pretium', 46.73, 12);
insert into product (name, category, description, price, stock) values ('Dusicyon thous', 'Juguetes', 'morbi a ipsum integer', 1088.75, 13);
insert into product (name, category, description, price, stock) values ('Lybius torquatus', 'Juguetes', 'sollicitudin mi sit amet lobortis sapien sapien non mi integer', 2320.62, 14);
insert into product (name, category, description, price, stock) values ('Laniarius ferrugineus', 'Juguetes', 'rutrum ac lobortis vel dapibus', 1273.2, 15);
insert into product (name, category, description, price, stock) values ('Petaurus norfolcensis', 'Juguetes', 'velit nec nisi vulputate nonummy maecenas tincidunt lacus', 1439.98, 16);
insert into product (name, category, description, price, stock) values ('Leptoptilos crumeniferus', 'Juguetes', 'nullam orci pede venenatis', 2474.1, 17);
insert into product (name, category, description, price, stock) values ('Capreolus capreolus', 'Juguetes', 'ac neque duis bibendum', 659.88, 18);
insert into product (name, category, description, price, stock) values ('Fulica cristata', 'Juguetes', 'odio justo sollicitudin ut suscipit a', 1759.25, 19);
insert into product (name, category, description, price, stock) values ('Drymarchon corias couperi', 'Juguetes', 'dui vel sem sed sagittis nam congue risus', 2339.91, 20);
insert into product (name, category, description, price, stock) values ('Tachyglossus aculeatus', 'Juguetes', 'nisl duis ac', 106.6, 21);
insert into product (name, category, description, price, stock) values ('Physignathus cocincinus', 'Juguetes', 'quam fringilla rhoncus mauris enim', 1255.81, 22);
insert into product (name, category, description, price, stock) values ('Gekko gecko', 'Juguetes', 'duis bibendum felis sed interdum venenatis turpis enim blandit', 527.61, 23);
insert into product (name, category, description, price, stock) values ('Panthera leo', 'Juguetes', 'sapien cum sociis natoque penatibus et', 2846.07, 24);
insert into product (name, category, description, price, stock) values ('Pycnonotus nigricans', 'Juguetes', 'in sapien', 2835.0, 25);
insert into product (name, category, description, price, stock) values ('Francolinus coqui', 'Juguetes', 'eleifend pede libero quis', 1004.45, 26);
