insert into CATEGORY (name, discount) values ('Juguetes', 20);
insert into CATEGORY (name, discount) values ('Libros', 15);
insert into CATEGORY (name, discount) values ('Deportes', 5);
insert into CATEGORY (name, discount) values ('Comida', 25);
insert into CATEGORY (name, discount) values ('Ropa', 35);
insert into CATEGORY (name, discount) values ('Otros', 0);

insert into product (name, description, price, stock, category_id) values ('Klarika', 'Other superficial bite of left great toe, subs encntr', 93, 68, 4);
insert into product (name, description, price, stock, category_id) values ('Shepard', 'Injury of nerves at ankle and foot level, left leg, sequela', 4, 465, 4);
insert into product (name, description, price, stock, category_id) values ('Evelin', 'Animal-rider injured in collision w ped/anml, subs', 81, 4, 5);
insert into product (name, description, price, stock, category_id) values ('Laverna', 'Unspecified foreign body in trachea causing other injury', 9, 107, 4);
insert into product (name, description, price, stock, category_id) values ('Ives', 'Nondisp fx of lateral condyle of unsp tibia, 7thD', 95, 377, 6);
insert into product (name, description, price, stock, category_id) values ('Pen', 'Other bursitis, not elsewhere classified, unspecified site', 1, 209, 3);
insert into product (name, description, price, stock, category_id) values ('Halsey', 'Insect bite (nonvenomous) of unspecified thumb, sequela', 34, 193, 3);
insert into product (name, description, price, stock, category_id) values ('Kristal', 'Blister of left eyelid and periocular area, sequela', 52, 43, 6);
insert into product (name, description, price, stock, category_id) values ('Ingunna', 'Corrosion of first deg mult sites of unsp wrs/hnd, sequela', 6, 298, 5);
insert into product (name, description, price, stock, category_id) values ('Bliss', 'External constriction of right hand, sequela', 15, 277, 6);
insert into product (name, description, price, stock, category_id) values ('Odessa', 'Crushed betw sailboat and oth wtrcrft/obj due to clsn, init', 81, 373, 3);
insert into product (name, description, price, stock, category_id) values ('Ogdon', 'Maternal care for excess fetal growth, unsp trimester, oth', 14, 404, 2);
insert into product (name, description, price, stock, category_id) values ('Neel', 'Nondisp fx of med wl of unsp acetab, subs for fx w nonunion', 46, 56, 1);
insert into product (name, description, price, stock, category_id) values ('Lynette', 'Allergic dermatitis of unspecified eye, unspecified eyelid', 88, 158, 4);
insert into product (name, description, price, stock, category_id) values ('Niall', 'Disp fx of distal phalanx of left thumb, init for opn fx', 53, 322, 5);
insert into product (name, description, price, stock, category_id) values ('Hettie', 'Underdosing of crbnc-anhydr inhibtr, benzo/oth diuretc, subs', 89, 206, 1);
insert into product (name, description, price, stock, category_id) values ('Berne', 'Corrosion of unsp degree of right toe(s) (nail), subs encntr', 29, 330, 3);
insert into product (name, description, price, stock, category_id) values ('Kizzie', 'Hemiplegic migraine, intractable', 44, 212, 4);
insert into product (name, description, price, stock, category_id) values ('Arnuad', 'Nondisp transverse fx shaft of unsp ulna, 7thJ', 54, 249, 4);
insert into product (name, description, price, stock, category_id) values ('Jasmina', 'Unspecified color vision deficiencies', 21, 375, 6);
insert into product (name, description, price, stock, category_id) values ('Earle', 'Nondisp transverse fx shaft of l femr, 7thD', 82, 386, 1);
insert into product (name, description, price, stock, category_id) values ('Koren', 'Disp fx of coronoid pro of unsp ulna, 7thG', 37, 157, 2);
insert into product (name, description, price, stock, category_id) values ('Ker', 'Burn of second degree of right toe(s) (nail)', 2, 271, 3);
insert into product (name, description, price, stock, category_id) values ('Erhard', 'Poisoning by antidiarrheal drugs, accidental, subs', 42, 73, 1);
insert into product (name, description, price, stock, category_id) values ('Doria', 'Traum hemor cereb, w LOC of 30 minutes or less', 89, 102, 6);
insert into product (name, description, price, stock, category_id) values ('Dylan', 'Sltr-haris Type IV physl fx low end humer, r arm, 7thG', 80, 205, 1);
insert into product (name, description, price, stock, category_id) values ('Ailis', 'Unsp agents primarily affecting the cardiovascular system', 72, 151, 3);
insert into product (name, description, price, stock, category_id) values ('Reggie', 'Penetrating wound w/o foreign body of unsp eyeball, sequela', 9, 449, 6);
insert into product (name, description, price, stock, category_id) values ('Tomkin', 'Person outsd hv veh inj in clsn w nonmtr veh nontraf, subs', 4, 118, 1);
insert into product (name, description, price, stock, category_id) values ('Colas', 'Insect bite (nonvenomous) of left ear', 6, 47, 1);
insert into product (name, description, price, stock, category_id) values ('Risa', 'Unsp fx shaft of humerus, right arm, subs for fx w nonunion', 87, 200, 2);
insert into product (name, description, price, stock, category_id) values ('Olly', 'Inj adductor musc/fasc/tend right thigh, sequela', 61, 370, 6);
insert into product (name, description, price, stock, category_id) values ('Garek', 'Nondisplaced transverse fracture of shaft of right tibia', 84, 280, 4);
insert into product (name, description, price, stock, category_id) values ('Whitney', 'Hematemesis', 32, 338, 5);
insert into product (name, description, price, stock, category_id) values ('Mario', 'Salpingo-oophoritis in pregnancy, unspecified trimester', 16, 355, 4);
insert into product (name, description, price, stock, category_id) values ('Orrin', 'Unspecified nondisp fx of surgical neck of right humerus', 40, 492, 1);
insert into product (name, description, price, stock, category_id) values ('Lucia', 'Implnt of artif int dev cause abn react/compl, w/o misadvnt', 70, 119, 2);
insert into product (name, description, price, stock, category_id) values ('Elinor', 'Toxic effect of chromium and its compounds, assault, subs', 10, 441, 5);
insert into product (name, description, price, stock, category_id) values ('Eustacia', 'Drown after fall into swimming pool, undet intent, sequela', 49, 148, 5);
insert into product (name, description, price, stock, category_id) values ('Raye', 'Nondisp oblique fx shaft of humer, r arm, 7thG', 57, 317, 1);
insert into product (name, description, price, stock, category_id) values ('Karyl', 'Path fx in oth disease, l humerus, subs for fx w nonunion', 49, 439, 3);
insert into product (name, description, price, stock, category_id) values ('Timmi', 'Driver of pk-up/van inj in clsn w oth mv nontraf, sequela', 58, 116, 3);
insert into product (name, description, price, stock, category_id) values ('Harwell', 'Oth diabetes w mild nonprlf diabetic rtnop w macular edema', 96, 114, 4);
insert into product (name, description, price, stock, category_id) values ('Wilfred', 'Corrosion of second degree of right knee, subs encntr', 98, 305, 3);
insert into product (name, description, price, stock, category_id) values ('Padget', 'Disp fx of lesser tuberosity of unspecified humerus, sequela', 15, 161, 4);
insert into product (name, description, price, stock, category_id) values ('Michaeline', 'Displaced fracture of shaft of unspecified clavicle, sequela', 85, 1, 1);
insert into product (name, description, price, stock, category_id) values ('Benedict', 'Subluxation of T2/T3 thoracic vertebra, subsequent encounter', 75, 102, 3);
insert into product (name, description, price, stock, category_id) values ('Cindra', 'Superficial frostbite of left toe(s), subsequent encounter', 66, 290, 3);
insert into product (name, description, price, stock, category_id) values ('Brittaney', 'Crohn''s disease, unspecified, with fistula', 96, 67, 5);
insert into product (name, description, price, stock, category_id) values ('Liza', 'Insect bite of right eyelid and periocular area, sequela', 64, 255, 5);
insert into product (name, description, price, stock, category_id) values ('Hobie', 'Glaucoma secondary to eye trauma, right eye, severe stage', 31, 124, 1);
insert into product (name, description, price, stock, category_id) values ('Worthington', 'Burn of first degree of thumb (nail)', 59, 405, 1);
insert into product (name, description, price, stock, category_id) values ('Devinne', 'Other superficial bite of unspecified ear', 36, 481, 2);
insert into product (name, description, price, stock, category_id) values ('Jae', 'Other fracture of shaft of radius', 68, 390, 6);
insert into product (name, description, price, stock, category_id) values ('Odo', 'Tubulo-interstitial neuropath in sys lupus erythematosus', 10, 400, 6);
insert into product (name, description, price, stock, category_id) values ('Cherianne', 'Nondisp transverse fracture of shaft of humerus, right arm', 24, 433, 6);
insert into product (name, description, price, stock, category_id) values ('Hubey', 'Lacerat great saphenous at low leg level, unsp leg, sequela', 72, 402, 6);
insert into product (name, description, price, stock, category_id) values ('Marcel', 'Other pre-existing diabetes mellitus in pregnancy', 54, 251, 2);
insert into product (name, description, price, stock, category_id) values ('Eachelle', 'Unsp injury to L4 level of lumbar spinal cord, sequela', 97, 37, 1);
insert into product (name, description, price, stock, category_id) values ('Torin', 'Sudden idiopathic hearing loss, left ear', 71, 490, 1);
insert into product (name, description, price, stock, category_id) values ('Atlanta', 'Crush betw unsp wtrcrft and oth wtrcrft/obj d/t clsn, init', 14, 264, 4);
insert into product (name, description, price, stock, category_id) values ('Zaccaria', 'Pathological fracture, left foot, init encntr for fracture', 71, 135, 2);
insert into product (name, description, price, stock, category_id) values ('Jehu', 'Burn due to passenger ship on fire, initial encounter', 30, 239, 3);
insert into product (name, description, price, stock, category_id) values ('Sibyl', 'Posterior tibial tendinitis', 16, 437, 4);
insert into product (name, description, price, stock, category_id) values ('Rodrigo', 'Oth fx unsp low leg, subs for opn fx type 3A/B/C w malunion', 12, 185, 1);
insert into product (name, description, price, stock, category_id) values ('Eliza', 'Underdosing of antifungal antibiotics, sys used, sequela', 25, 69, 4);
insert into product (name, description, price, stock, category_id) values ('Darell', 'Laceration of unsp kidney, unspecified degree, subs encntr', 10, 112, 4);
insert into product (name, description, price, stock, category_id) values ('Justino', 'Other specified disorders of amniotic fluid and membranes', 99, 293, 1);
insert into product (name, description, price, stock, category_id) values ('Shoshana', 'Erectile dysfunction due to arterial insufficiency', 6, 313, 4);
insert into product (name, description, price, stock, category_id) values ('Rubie', 'Oth parlyt synd fol unsp cerebvasc dis aff right nondom side', 83, 374, 6);
insert into product (name, description, price, stock, category_id) values ('Bethina', 'Path fx, unsp ulna and radius, subs for fx w routn heal', 70, 293, 2);
insert into product (name, description, price, stock, category_id) values ('Alene', 'Nodular corneal degeneration, unspecified eye', 32, 130, 4);
insert into product (name, description, price, stock, category_id) values ('Orran', 'Premature separation of placenta, unspecified', 45, 210, 1);
insert into product (name, description, price, stock, category_id) values ('Doralynne', 'Nondisp pilon fx r tibia, 7thN', 52, 226, 1);
insert into product (name, description, price, stock, category_id) values ('Rosemonde', 'Contracture, unspecified hip', 6, 111, 3);
insert into product (name, description, price, stock, category_id) values ('Rainer', 'Corrosion of second degree of left knee, subs encntr', 45, 9, 2);
insert into product (name, description, price, stock, category_id) values ('Carola', 'Unsp dislocation of left ulnohumeral joint, init encntr', 89, 163, 4);
insert into product (name, description, price, stock, category_id) values ('Carmina', 'Other disorders of continuity of bone, left ulna', 4, 206, 4);
insert into product (name, description, price, stock, category_id) values ('Nobie', 'Prsnl hx of malig neoplm of rectum, rectosig junct, and anus', 24, 116, 2);
insert into product (name, description, price, stock, category_id) values ('Helga', 'Laceration without foreign body, right hip', 6, 220, 6);
insert into product (name, description, price, stock, category_id) values ('Jaquith', 'Mech compl of surgically created AV fistula, sequela', 78, 168, 2);
insert into product (name, description, price, stock, category_id) values ('Zebadiah', 'Toxic effect of cntct w oth venom animals, slf-hrm, sequela', 85, 370, 6);
insert into product (name, description, price, stock, category_id) values ('Sharai', 'Comminuted fracture of shaft of tibia', 95, 412, 2);
insert into product (name, description, price, stock, category_id) values ('Shalom', 'Dislocation of C7/T1 cervical vertebrae, sequela', 63, 407, 3);
insert into product (name, description, price, stock, category_id) values ('Payton', 'Fracture of r shoulder girdle, part unsp, init for opn fx', 30, 268, 3);
insert into product (name, description, price, stock, category_id) values ('Mellisent', 'Amyloidosis', 1, 450, 3);
insert into product (name, description, price, stock, category_id) values ('Pippy', 'Physical medicine devices associated with adverse incidents', 6, 490, 2);
insert into product (name, description, price, stock, category_id) values ('Vivyan', 'Other acute nonsuppurative otitis media', 1, 77, 3);
insert into product (name, description, price, stock, category_id) values ('Arline', 'Oth fx head/neck of r femr, 7thH', 17, 283, 3);
insert into product (name, description, price, stock, category_id) values ('Theresina', 'Abscess of tendon sheath, left thigh', 28, 114, 3);
insert into product (name, description, price, stock, category_id) values ('Diann', 'Adverse effect of unsp prim sys and hematolog agent, subs', 36, 91, 5);
insert into product (name, description, price, stock, category_id) values ('Jany', 'Injury of other iliac blood vessels, subsequent encounter', 21, 427, 4);
insert into product (name, description, price, stock, category_id) values ('Addie', 'Milt op involving oth dest arcrft, civilian, init', 42, 432, 4);
insert into product (name, description, price, stock, category_id) values ('Myer', 'Open bite of left upper arm, sequela', 22, 381, 5);
insert into product (name, description, price, stock, category_id) values ('Ezequiel', 'Oth fx upper end of r tibia, subs for clos fx w routn heal', 72, 40, 2);
insert into product (name, description, price, stock, category_id) values ('Hattie', 'Activity, oth involving climbing, rappelling and jumping off', 87, 11, 2);
insert into product (name, description, price, stock, category_id) values ('Alice', 'Burn unsp deg of unsp site left lower limb, ex ank/ft, init', 9, 488, 2);
insert into product (name, description, price, stock, category_id) values ('Doria', 'Leakage of other urinary catheter', 86, 240, 2);
insert into product (name, description, price, stock, category_id) values ('Cy', 'Laceration of ovary, bilateral, subsequent encounter', 23, 408, 5);
insert into product (name, description, price, stock, category_id) values ('Shina', 'Burn unsp degree of unsp site unsp lower limb, except ank/ft', 64, 379, 4);